# railway.toml

[build]
# Configura los pasos necesarios para construir tu proyecto Symfony
commands = [
    "composer install --no-dev --optimize-autoloader",  # Instalar dependencias de producción
    "php bin/console cache:clear --env=prod",           # Limpiar y compilar la caché de Symfony
    "php bin/console doctrine:migrations:migrate --no-interaction --env=prod"  # Ejecutar migraciones
]

[start]
# Comando para iniciar el servidor web en Railway
command = "php -S 0.0.0.0:80 -t public"
